
version: '3'

services:
  mongod:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
    volumes:
      - ./docker/data/mongod:/root/data
      - ./docker/logs/mongod:/root/logs
      - ./docker/mongo/mongod.conf:/etc/mongod.conf
    entrypoint: ["mongod","--config","/etc/mongod.conf"]
    ports:
      - 27017:27017
  app:
      build: .
      image: node_backend
      restart: always
      volumes:
          - ./:/app
          - /app/node_modules
      ports:
        - ${APP_EXPOSED_PORT:-0}:3000
      depends_on:
        - mongod