
version: '3'

services:
  mongodb:
    image: mongo:7.0.9-rc0
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongo:/data/db
    networks:
      - node-network
  app:
      build: .
      image: node_backend
      restart: always
      volumes:
          - ./:/app
          - /app/node_modules
      ports:
        - ${APP_EXPOSED_PORT:-0}:3000
      depends_on:
        - mongodb
      networks:
        - node-network

networks:
  node-network:
    driver: bridge